module.exports = {
  allJS: './dev/**/*.js',
  allCSS: [
    "dev/ia/css/bootstrap-slider.min.css",
    "dev/ia/css/owl.carousel.css",
    "dev/ia/css/uikit.css",
    "dev/ia/css/sticky.min.css",
    "dev/ia/css/slidenav.css",
    "dev/ia/css/inhouse.css",
    "dev/ia/icons/property-icons/ih-icons.css",
    "dev/ic/about/css/about.css",
    "dev/ic/featured-listings/css/featured-listings.css",
    "dev/ic/landing-search/css/search.css",
    "dev/ic/listing-loader/css/listing-loader.css",
    "dev/ic/navbar/css/navbar.css",
    "dev/ic/slider/css/slider.css",
    "dev/ic/resources/css/resources.css",
    "dev/ic/testimonials/css/testimonials.css",
    "dev/ic/contact/css/contact.css",
    "dev/ic/partners/css/partners.css",
    "dev/ic/footer/css/footer.css",
    "dev/ic/listing-details/css/listing-details.css",
    "dev/ic/divider/css/divider.css",
    "dev/ic/like-button/css/like-button.css",
    "dev/ic/visitor-modal/css/visitor-modal.css",
    "dev/ic/amenities/css/amenities.css",
    "dev/ic/listing-map/css/listing-map.css",
    "dev/ic/nearby/css/nearby.css",
    "dev/ic/photo-slider/css/photo-slider.css",
    "dev/ic/about-listing/css/about-listing.css",
    "dev/ip/bios/css/ip-bios.css",
    "dev/ip/contact/css/ip-contact.css",
    "dev/ip/content/css/ip-content.css",
    "dev/ip/journal/css/ip-journal.css",
    "dev/ip/listing/css/ip-listing.css",
    "dev/ip/narratives/css/ip-narratives.css",
    "dev/ip/results/css/ip-results.css",
    "dev/ip/search/css/ip-search.css",
    "dev/ip/subdivisions/css/ip-subdivisions.css",
    "dev/ip/system/css/ip-system.css"
  ],
  frameworkComponents: 'dev/ic/**/*.js',
  frameworkMain: 'dev/is/app.js',
  frameworkTemplates: './dev/**/*.htm',
  pugTemplates: './dev/**/*.pug',
  vendorFiles: './ia/js/*.js'
};
